server:
  port:3306

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://118.178.235.119/asdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    # 超时时间
    timeout: 10000ms
    # 服务器地址
    host: 118.178.235.119
    # 服务器端口
    port: 6379
    # 数据库
    database: 0
    # 客户端
    lettuce:
      pool:
        # 最大连接数
        max-active: 1024
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000
        # 最大空闲连接
        max-idle: 200
        # 最短空闲时间
        min-idle: 5

    # rabbitmq 配置
    rabbitmq:
      # 用户名
      username: guest
      # 密码
      password: guest
      # 服务器地址
      host: 118.178.235.119
      # 端口
      port: 15672
      # 消息确认回调
      publisher-confirm-type: correlated
      # 消息失败回调
      publisher-returns: true


mybatis:
  mapper-locations: classpath:mapper/*.xml